---
- name: install mysql
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - mysql-server

- name: copy .my.cnf
  template:
    src: ../../templates/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    mode: 644

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Create database
  mysql_db: db=kalolodev state=present

- name: Creating kalolo user on hosts {{ box_ip }}
  mysql_user: name=kalolo password=devtest priv=*.*:ALL state=present host={{ item }}
  with_items:
    - "{{ box_ip }}"
    - 127.0.0.1
    - 192.168.50.9
    - 192.168.50.1
    - ::1
    - localhost
    - "*"
