# vagrant_config.yml
boxconfig:
  name: local.dev
  box: ubuntu/trusty64
  ram: 2048
  ip: 192.168.50.9
  apache_projects:
      www: "/Users/kalolo/projects/www/html"
      laravel: "/Users/kalolo/projects/www/laravel-projects"
